egraphs-good/egglog-python

conftest.py, pyproject.toml, python/tests/test_typing.py, test-data/unit/check-basic.test
This adds support for verifying that certain code type checks and that certain code doesn't. This allows us to verify that are typings are behaving as they should.
It does this by re-using MyPy's builtin testing framework which is documented here:
https://github.com/python/mypy/blob/master/test-data/unit/README.md
The only other project I found which does this is the SQLAlchemy stubs: https://github.com/angaza/sqlalchemy-stubs/blob/6af1f077745e91d8a4ca624e19cdcf7082aaabdf/test/testsql.py
It ops for another approach however. Instead of reusing the TypeChecker test from MyPy, it builds a new test case that calls out to the MyPy CLI. I choose instead to re-use that test case, so that hopefully it would stay up to date more cleanly.
---
I wanted to get this working for my in progress higher …
=> Add support for verifying types using mypy's unit testing 

README.md
I tried to change the RTD link to update the package, but I wasn't able to rename it.
=> Fix RTD link in readme

Cargo.lock, Cargo.toml, docs/changelog.md, python/egglog/builtins.py, python/tests/test_high_level.py
Now that upstream `egglog` supports `neg` for `f64` (https://github.com/egraphs-good/egglog/pull/168), this PR adds support to the `f64` sort in these bindings.
Closes #32
=> Add support for negation to f64

docs/changelog.md, python/egglog/egraph.py
The `birewrite` command wasn't exposed by accident, so couldn't be imported from the `egglog` module.
Thanks [Erick Ochoa for reporting](https://egraphs.zulipchat.com/#narrow/stream/375765-egglog/topic/Python.20bindings/near/401628934).
=> Fix exposing birewrite

python/egglog/builtins.py, python/egglog/exp/array_api.py
Builds on #76 to switch the Array API to just generate egglog primitives instead of pyobjects, to make the graphs smaller.
=> Switch array api to gen primitives instead of pyobjects

docs/changelog.md, python/egglog/declarations.py, python/egglog/egraph.py
This PR builds on #78 to make the names in the visualizations shorter, by using the Python names instead of the egglog names. Also for methods that are operators, it uses the inline operator, i.e. `+` instead of the method name `__add__`.
Before:
After:
=> Update visualization names

python/egglog/declarations.py
Switch methods to visualize in the form `{self}.{method}(...)` instead of `{class_name}.{method}({self}, ...)` to make them more succinct
=> Dont use class name for methods

docs/changelog.md, python/egglog/egraph.py, python/egglog/runtime.py, python/tests/test_high_level.py
Closes #84 by upcasting subsequent passed rewrite, eq, etc to the type of the first arg.
=> Add support for upcasting when passing args to rewrite, eq, etc

Cargo.lock, Cargo.toml, docs/changelog.md, docs/reference/python-integration.md, python/egglog/builtins.py, python/egglog/egraph.py, python/tests/test_high_level.py
Moves `EGraph.eval_fn` to standalone `py_eval_fn` b/c we don't need egraph anymore after PyObject refactor.
=> Move py eval fn

docs/changelog.md, docs/reference/egglog-translation.md, docs/reference/python-integration.md, python/egglog/declarations.py, python/egglog/egraph.py, python/egglog/examples/bool.py, python/egglog/examples/lambda_.py, python/egglog/examples/resolution.py, python/egglog/exp/array_api.py, python/egglog/exp/array_api_program_gen.py, python/egglog/exp/program_gen.py, python/egglog/runtime.py, python/tests/test_array_api.py, python/tests/test_high_level.py, test-data/unit/check-high-level.test
This PR changes how you emit the `!=` egglog function. Previously, you would use the `__ne__`/`x !=y` method to create it; with this PR, it is moved to a standalone function `ne(x).to(y)`.
This allows custom classes to override `__ne__` to support custom expressions, like how, on arrays, it would return an array of booleans. It also unifies it with the `eq` function, which behaves similarly.
This is a breaking change, and I could have instead preserved the `__ne__` behavior on existing classes and allowed a custom operator on override. This would have been backward compatible, but I thought it was slightly more subtle. Also, for classes that have a custom `__ne__`, they might also want to emit the builtin `!=` function, so we would need another way of creating that as well.
Happy for any …
=> Move != to function instead of method

python/egglog/egraph.py, python/tests/test_high_level.py
Previously, if you did something like `x: str` in a classbody there would be an odd error, since it wouldn't be able to resolve the `__egg_decls__`. This fixes it to be more descriptive.
Thanks for raising Adrian on Zulip: https://egraphs.zulipchat.com/#narrow/stream/375765-egg.2Fegglog/topic/First.20time.20user.20of.20python.20bindings/near/421756317
=> Improve error messages when using non classvar type annotation

docs/changelog.md, pyproject.toml, python/tests/test_bindings.py, python/tests/test_high_level.py, python/tests/test_modules.py, src/serialize.rs, src/utils.rs
This PR is meant to make the low level bindings thread safe so that they work with the colab debugger.
Should ideally address #128.
=> Make low level bindings thread safe

.github/workflows/CI.yml, .github/workflows/version.yml, increment_version.py
This PR tries moving all the version release stuff to separate action, that will create a new PR for that version. We can't push to main in a gitbub action because of branch protections
=> Try moving all releases to the bump version step

.github/workflows/CI.yml, docs/changelog.md, docs/reference/python-integration.md, pyproject.toml, python/egglog/bindings.pyi, python/egglog/builtins.py, python/egglog/conversion.py, python/egglog/declarations.py, python/egglog/egraph.py, python/egglog/egraph_state.py, python/egglog/exp/array_api.py, python/egglog/pretty.py, python/egglog/runtime.py, python/egglog/thunk.py, python/tests/test_high_level.py, python/tests/test_runtime.py, python/tests/test_unstable_fn.py, src/egraph.rs
This PR adds support for passing functions at the high level API.
All functions need to be wrapped in the `UnstableFn` wrapper, like you need to do in egglog currently. In a follow up PR I will remove this restriction. That way the public API will allow you to use `Callable` as an argument and it will work properly.
TODOs after this:
=> Add initial support for functions at the high level

Cargo.lock, docs/changelog.md, docs/reference/python-integration.md, python/egglog/builtins.py, python/egglog/conversion.py, python/egglog/egraph.py, python/egglog/examples/higher_order_functions.py, python/egglog/functionalize.py, python/egglog/runtime.py, python/tests/test_functionalize.py, python/tests/test_unstable_fn.py
This allows you to pass a normal Python function (not decorated in @function) to higher order egglog functions.
=> Add support for transforming normal Python functions

docs/reference/python-integration.md, python/egglog/builtins.py, python/egglog/egraph.py, python/egglog/pretty.py, python/egglog/runtime.py, python/egglog/thunk.py, python/tests/test_runtime.py, python/tests/test_unstable_fn.py
This PR makes unwrapped functions be named as their bodies, instead of assigning a unique ID to them.
This makes it easier to see them in the graph view and makes them de-duplicate based on the body. See https://egraphs.zulipchat.com/#narrow/stream/375765-egg.2Fegglog/topic/Anonymous.20Functions.20in.20Egglog for more details.
=> Name anon functions based on bodys

.github/workflows/version.yml
Thanks you for the awesome project! I was doing some hunting, and noticed that prebuilt wasn't available across all platforms, so I thought I'd take a stab. Given your use of [maturin-paction](https://github.com/PyO3/maturin-action) [this PR](https://github.com/PyO3/maturin/pull/273/files), and [this documentation change](https://github.com/PyO3/maturin-action#manylinux-docker-container) it appears like adding qemu will provide platform support.
Hopefully this helps, and thanks a tonne for the project!!
=> manylinux support

python/egglog/egraph.py, python/tests/test_no_import_star.py
closes https://github.com/egraphs-good/egglog-python/issues/210
=> Fix usage when not importing all from egglog

.github/workflows/CI.yml, docs/changelog.md, python/egglog/egraph_state.py, python/egglog/exp/array_api_jit.py, python/egglog/exp/array_api_program_gen.py, python/egglog/exp/program_gen.py, python/tests/__snapshots__/test_array_api/TestLDA.test_source_optimized.py, python/tests/test_array_api.py, python/tests/test_program_gen.py
Move around rulesets so we can generate array API example for egglog benchmarks/tests in an automated way https://github.com/egraphs-good/egglog/pull/444
=> Be able to generate egg from python example

.github/workflows/version.yml
Having done some digging, the various wheels published to pypy don't include arm (Linux). This is my fault.
Looking at [this example](https://github.com/messense/crfs-rs/blob/b118948df13e3d3b1ea8dc73e3088319e5f02b04/.github/workflows/Python.yml#L96), it appears rather different than the documented change we made in #199.
Sorry about this @saulshanabrook. Hope this helps.
=> arm matrix

.github/workflows/CI.yml, pyproject.toml
Given the quick read I'd done of the dependencies, it appears that this library should work on python 3.13. I went for a very lazy CI change and adding the trove, thinking that if this passes, it might be useful to others.
Similarly, if this fails, by all means kill the PR :D
=> Python 3.13 Trove and CI

pyproject.toml, python/egglog/declarations.py
Fixes #244, As suggested this fixes the problem of hash collisions (and specifically the `hash(-1) == hash(-2)` case).
Benchmark shows no change for either the original suggested change or the slightly more optimized one, but it seems reasonable to use it in the improved form.
There is also a change to the pyproject.toml - adding a version, which seemed required to get the CI to work for me
=> CallDecl __eq__ Fix

python/egglog/egraph.py, python/egglog/runtime.py
Hi,
I just upgraded to python 3.13, and noticed that the library threw some exceptions on start up. After a bit of digging, I reached these ignore lists for reflected attributes, and added the offending ones which were added in python 3.13.
I'm actually not sure why it failed for me and the CI tests for python 3.13 seem to pass, if you can shed some light on that?
(edit: in fact, I'm also not sure how python 3.10 tests pass, since egraph.py:20 imports typing.Never which is introduced in 3.11?)
Let me know if I got it right, I'm not sure I understand the entire runtime 😄
=> Fix python 3.13 support

python/tests/test_array_api.py
This PR simplifies the current benchmarks and makes them more accurate, so that if they are run in multiple iterations things won't be improperly cached.
=> More accurate local benchmarking

docs/changelog.md, python/egglog/builtins.py, python/egglog/conversion.py, python/egglog/declarations.py, python/egglog/egraph.py, python/egglog/egraph_state.py, python/egglog/examples/bignum.py, python/egglog/examples/multiset.py, python/egglog/runtime.py, python/egglog/type_constraint_solver.py, python/tests/test_high_level.py, python/tests/test_type_constraint_solver.py
Adds bindings for new builtins. This required some generalizations to the current type resolver to support the `map` function on multisets
=> Add multiset, bigint, bigrat builtins

python/egglog/egraph.py, python/egglog/egraph_state.py, python/egglog/exp/array_api.py, python/egglog/exp/array_api_jit.py, python/egglog/exp/array_api_program_gen.py, python/tests/__snapshots__/test_array_api/test_jit[lda][expr].py, python/tests/__snapshots__/test_array_api/test_jit[lda][initial_expr].py, python/tests/test_array_api.py, src/egraph.rs
This PR changes the logic for jitting a little bit so that we can easily emit egglog source code that doesn't contain any pyobject or Rational calls. That way it can be used in upstream core egglog as a benchmark
=> Easily create pure egglog output of jitted function

Cargo.lock, docs/changelog.md, docs/index.md, python/egglog/__init__.py, python/egglog/builtins.py, python/egglog/conversion.py, python/egglog/egraph.py, python/egglog/examples/bignum.py, python/egglog/examples/eqsat_basic.py, python/egglog/examples/multiset.py, python/egglog/exp/array_api.py, python/egglog/exp/array_api_jit.py, python/tests/test_array_api.py, python/tests/test_high_level.py, python/tests/test_program_gen.py
In https://github.com/egraphs-good/egglog-python/pull/265 (released as 9.0.0) the ability to automatically extract a builtin using a global egraph context was added. This PR removes that feature, requiring all builtins to be in a normalized form.
I realized that for https://github.com/egraphs-good/egglog-python/issues/241 we want facts to compare structural equality when converting to a boolean, instead of using the e-graph. Looking at that previous PR, it seems like a mistake to add this implicit context, making things more confusing and opaque with minimal UX improvements.
=> Remove automatic extraction in builtin evaluation

Cargo.lock, docs/changelog.md, pyproject.toml, python/egglog/builtins.py, python/egglog/egraph.py, python/egglog/examples/higher_order_functions.py, python/egglog/examples/lambda_.py, python/egglog/exp/array_api.py, python/tests/test_no_import_star.py, python/tests/test_pretty.py, python/tests/test_unstable_fn.py
Closes #283 by fixing a runtime type resolution bug.
This also stops special casing adding `Callable` as global for type resolution and instead forces you to import all builtins and other types at runtime.
=> Fix bug resolving types

.github/workflows/CI.yml
Try to fix the CI tests by running properly on different Python versions. Found by https://github.com/egraphs-good/egglog-python/issues/295
=> Fix tests not running on different Python version

.github/workflows/CI.yml, docs/changelog.md, python/egglog/declarations.py, python/egglog/egraph.py, python/egglog/exp/array_api.py, python/egglog/runtime.py, python/egglog/thunk.py, python/egglog/type_constraint_solver.py, python/egglog/version_compat.py, python/tests/test_high_level.py
Fixes https://github.com/egraphs-good/egglog-python/issues/295
- Only use `add_note` on exceptions where it's supported
- monkeypatch generic typing on 3.10 to support typevars
=> Fix python 3.10 compat

.github/workflows/version.yml, Cargo.lock, Cargo.toml, src/conversions.rs, src/egraph.rs, src/lib.rs
Speedup new backend by using only one thread and a custom memory allocator Copied from https://github.com/egraphs-good/egglog/pull/637
=> Speedup new backend

.github/workflows/CI.yml
Ran out of free minutes and need to wait to set up custom github action runner to re-enable.
=> Remove walltime benchmarking for now

Cargo.lock, Cargo.toml, python/egglog/bindings.pyi, python/egglog/egraph.py, python/egglog/egraph_state.py, python/egglog/exp/array_api.py, python/tests/test_bindings.py, python/tests/test_py_object_sort.py, src/conversions.rs, src/egraph.rs, src/lib.rs, src/serialize.rs
Bump egglog version which changes running commands to return structured output and adds fields on the serialized e-graph to show if functions were omitted.
Follow up PRs will expose this functionality at the high level.
=> Bump Egglog version

docs/changelog.md, python/egglog/egraph.py, python/egglog/egraph_state.py, python/tests/test_high_level.py
Adds support for upstream egglog change to emit when serializing and functions or calls were omitted based on maxmimums
=> Emit warnings when functions omitted when visualizing

docs/changelog.md, docs/reference/egglog-translation.md, python/egglog/egraph.py, python/egglog/egraph_state.py, python/egglog/runtime.py, python/tests/test_high_level.py
Exposes `function-size` egglog command in Python. Handles also turning egglog function back into Python functions if no function name is specified and all functions should be checked.
=> Add `all_function_sizes` and `function_size` EGraph methods

.gitignore, docs/changelog.md, docs/reference/egglog-translation.md, python/egglog/declarations.py, python/egglog/egraph.py, python/egglog/egraph_state.py, python/egglog/examples/jointree.py, python/egglog/pretty.py, python/tests/test_high_level.py
This re-implements the syntactic macro in the egglog experimental to create a new table for each function to store its cost. It re-uses the custom extractor which looks up in this table.
I talked to @yihongz and we discussed different ways to implement this, from changing syntactic macros to take Expr instead of Sexpr, but settled on just having me re-implement the syntax.
Closes https://github.com/egraphs-good/egglog-python/issues/332
=> Add support for `set_cost` action to have row level costs for extraction
